FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD rbac-cloud-upms-biz.jar upms-biz.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /upms-biz.jar" ]