FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD rbac-cloud-regiter.jar regiter.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /regiter.jar" ]